### ISSUE TITLE
Log files opened with read-write permissions

### ISSUE THREAD

**Issue by wyldckat** [blueCFD/PyFoam#1]
For example:

```
$ pyFoamPlotWatcher log.simpleFoam
Traceback (most recent call last):
  File "D:/BLUECF~1.3/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamPlotWatcher.py", line 5, in <module>
    PlotWatcher()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PlotWatcher.py", line 44, in __init__
    **kwargs)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PyFoamApplication.py", line 348, in __init__
    result=self.run()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PlotWatcher.py", line 141, in run
    run.start()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\BasicWatcher.py", line 75, in start
    self.lineHandle(line)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\AnalyzedCommon.py", line 84, in lineHandle
    self.analyzer.analyzeLine(line)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\LogAnalysis\FoamLogAnalyzer.py", line 138, in analyzeLine
    self.analyzers[nm].doAnalysis(line)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\LogAnalysis\TimeLineAnalyzer.py", line 43, in doAnalysis
    self.notifyNewTime(m)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\LogAnalysis\TimeLineAnalyzer.py", line 32, in notifyNewTime
    self.notify(float(m.group(2)))
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\LogAnalysis\LogLineAnalyzer.py", line 65, in notify
    f(*data)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\LogAnalysis\FoamLogAnalyzer.py", line 84, in setTime
    listener.timeChanged()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\StepAnalyzedCommon.py", line 39, in timeChanged
    self.picklePlots()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\AnalyzedCommon.py", line 334, in picklePlots
    move(pickleFile+".tmp",pickleFile)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\ParaView-4.1.0\bin\Lib\shutil.py", line 300, in move
    os.unlink(src)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'log.simpleFoam.analyzed\\pickledPlots.tmp'
```

**Comment by wyldckat** [comment]
It's missing a `del pick` in `PyFoam/Execution/AnalyzedCommon.py`, before the move is made. This should also affect PyFoam on other platforms.
