### ISSUE TITLE
Plans for what needs to be done to get PyFoam up and running with blueCFD-Core 2016 and 2017

### ISSUE THREAD

**Issue by wyldckat** [blueCFD/PyFoam#10]
As far as I remember and know, one of the critical requirements for PyFoam to work on Windows is the need to rely on Python 3 instead of Python 2. This is because Python 3 has a lot of features that are needed by PyFoam on any operating system, which Python 2 does not have for Windows... that said, I was curious sometime ago and have tried installing pyFoam with pip3 with the following commands:

```
pacman -Sy
pacman -Ss pip
pacman -S mingw64/mingw-w64-x86_64-python3-pip
pip3 install pyfoam 
```

but unfortunately numpy failed to build in the same exact way as it did for you when using Python 2 (pip), something about "/GL-" not being found. Which means this is going to take some considerable time to get things to work properly.

**Comment by wyldckat** [comment]
Also for future reference, for those looking into this report, looking for instructions on how to install PyFoam on blueCFD-Core 2016 or 2017, please keep in mind the following details:

1. OpenFOAM 4 and 5 (provided with blueCFD-Core 2017) also has a script for monitoring residuals. The instructions on how to use them are provided in the OpenFOAM User Guide: https://cfd.direct/openfoam/user-guide/graphs-monitoring/  - there is also a video: https://www.youtube.com/watch?v=LY4jUg3lOoE

2. Gnuplot (which pyFoam needs for plotting) in blueCFD-Core 2017-1 is missing a few features, one of which is the missing of export capabilities for JPG and PNG. This has already been fixed in blueCFD-Core 2017-2, which is already available online. And it was working fine with blueCFD-Core 2016-1 and 2016-2.

**Comment by fcollonval** [comment]
Dear Bruno,

I successfully install PyFoam within python3 using blueCFD-Core 2017-2.

I install the mingw64 numpy package not letting pip handling the dependency:

In short I use the following commands
```
pacman -Sy
pacman -Ss pip
pacman -S mingw64/mingw-w64-x86_64-python3-pip
pacman -Ss numpy
pacman -S  mingw64/mingw-w64-x86_64-python3-numpy
pip3 install pyfoam 
```

Now as I have not used OpenFOAM since a couple of years. I don't have much test cases to try on. But I fail just using `pyFoamRunner.py` on the cavity tutorial case. The error is Windows related as stated in the error message:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:/CODES/blueCFD-Core-2017/msys64/mingw64/lib/python3.6\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:/CODES/blueCFD-Core-2017/msys64/mingw64/lib/python3.6/site-packages\PyFoam\Execution\FoamThread.py", line 200, in run
    close_fds=True)
  File "D:/CODES/blueCFD-Core-2017/msys64/mingw64/lib/python3.6\subprocess.py", line 624, in __init__
    "close_fds is not supported on Windows platforms"
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

I read in old posts that in the past you proposed some patches on PyFoam. Can you point out some ressources to figure out typical work around for unsupport Windows functions?

**Comment by akbalom** [comment]
Dear Collonval,

I have tried to install pyFoam on to BlueCFD. However, I got some problem with "pip3 install pyfoam" . BlueCFD terminal is said that bash: pip3 no command. 

What are the steps to install pyfoam on bluecfd? 
Thanks.

**Comment by wyldckat** [comment]
@akbalom: Unfortunately we have not yet managed to find the time needed to get PyFoam up and running again with blueCFD-Core. Therefore, even if you are able to install it based on @fcollonval's instructions, you will still get the error messages similar to the ones shown above, which means that PyFoam will still not work as intended.
