### ISSUE TITLE
Problem with Gnuplot "set terminal x11 noraise"

### ISSUE THREAD

**Issue by wyldckat** [blueCFD/PyFoam#3]
This was triggered after Issue #1 was fixed:

```

        G N U P L O T
        Version 4.6 patchlevel 3    last modified April 2013
        Build System: MS-Windows 32 bit 

        Copyright (C) 1986-1993, 1998, 2004, 2007-2013
        Thomas Williams, Colin Kelley and many others

        gnuplot home:     http://www.gnuplot.info
        faq, bugs, etc:   type "help FAQ"
        immediate help:   type "help"  (plot window: hit 'h')

Terminal type set to 'wxt'
gnuplot> set terminal windows
Terminal type set to 'windows'
Options are '0 color solid noenhanced'
gnuplot> set y2tics
gnuplot> set xlabel "Time [s]"
gnuplot> set terminal x11 noraise
Terminal type set to 'unknown'
                      ^
         unknown or ambiguous terminal type; type just 'set terminal' for a list

gnuplot> set ylabel "Cumulative"
gnuplot> set y2label "Global"
gnuplot> set title "Continuity"
gnuplot> 
```

**Comment by wyldckat** [comment]
Should use: `set terminal wxt noraise`
or: `set terminal windows`

**Comment by wyldckat** [comment]
The problem is that even after this is fixed, there was no plot... and there was no error message. Will check on Linux to check what it should do.

**Comment by wyldckat** [comment]
If executed from the WCL (Windows Command Line), hitting Ctrl+C will get me this output:

```
D:\blueCFD-Core-2.3\ofuser-2.3\run\tutorials\incompressible\simpleFoam\pitzDaily>pyFoamPlotWatcher --solver-not-running-anymore --traceback-on-error --har
dcopy log.simpleFoam
Watcher: Keyboard interrupt
Traceback (most recent call last):
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam/Scripts/pyFoamPlotWatcher.py", line 5, in <module>
    PlotWatcher()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PlotWatcher.py", line 44, in __init__
    **kwargs)
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PyFoamApplication.py", line 348, in __ini
t__
    result=self.run()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PlotWatcher.py", line 141, in run
    run.start()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\BasicWatcher.py", line 84, in start
    self.stopHandle()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\GnuplotRunner.py", line 88, in stopHandle
    self.timeHandle()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Execution\GnuplotRunner.py", line 278, in timeHandle
    self.plots[p].redo()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Basics\GeneralPlotTimelines.py", line 123, in redo
    self.doReplot()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Basics\GnuplotTimelines.py", line 129, in doReplot
    self.replot()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\ThirdParty\Gnuplot\_Gnuplot.py", line 335, in replot
    self.refresh()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\ThirdParty\Gnuplot\_Gnuplot.py", line 228, in refresh
    self(self.plotcmd + ' ' + ", ".join(plotcmds))
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\ThirdParty\Gnuplot\_Gnuplot.py", line 212, in __call__

    self.gnuplot(s)
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\ThirdParty\Gnuplot\gp_win32.py", line 130, in __call__

    self.write(s + '\n')
IOError: [Errno 22] Invalid argument
Terminate batch job (Y/N)? y

D:\blueCFD-Core-2.3\ofuser-2.3\run\tutorials\incompressible\simpleFoam\pitzDaily>
```

In addition, when compared to Linux, it should have given the output of the log file, at least the end of it and also show the plots.

**Comment by wyldckat** [comment]
Running with the dev option gave a bit more information:

```
D:\blueCFD-Core-2.3\ofuser-2.3\run\tutorials\incompressible\simpleFoam\pitzDaily>pyFoamPlotWatcher --solver-not-running-anymore --i-am-a-developer log.sim
pleFoam
Traceback (most recent call last):
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam/Scripts/pyFoamPlotWatcher.py", line 5, in <module>
    PlotWatcher()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PlotWatcher.py", line 44, in __init__
    **kwargs)
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PyFoamApplication.py", line 291, in __ini
t__
    signal.signal(signal.SIGUSR1,pyFoamSIG1HandlerPrintStack)
AttributeError: 'module' object has no attribute 'SIGUSR1'

> d:\bluecfd-core-2.3\thirdparty-2.3\platforms\linuxmingw-w64\pyfoam\lib\site-packages\pyfoam\applications\pyfoamapplication.py(291)__init__()
-> signal.signal(signal.SIGUSR1,pyFoamSIG1HandlerPrintStack)

```

**edit**: Never mind, see Issue #4.

**Comment by wyldckat** [comment]
If we hack the file `PyFoam\ThirdParty\Gnuplot\gp_win32.py` to use `gnuplot.exe` instead of `pgnuplot.exe`, were able to trigger the following error when we use Ctrl+C (in WCL):

```
Watcher: Keyboard interrupt
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031BA808>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031B9708>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031BA788>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031B9788>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031BA7C8>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031BA6C8>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'unlink'" in <bound method _NewFileItem.__del__ of <PyFoam.ThirdParty.Gnuplot.PlotItems._NewFileItem instanc
e at 0x00000000031BA708>> ignored
```
