### ISSUE TITLE
pyFoamCloneCase fails due to close_fds

### ISSUE THREAD

**Issue by wyldckat** [blueCFD/PyFoam#5]
The complete error message:

```
D:\blueCFD-Core-2.3\ofuser-2.3\run\tutorials\incompressible\simpleFoam>pyFoamCloneCase
Usage
=====
  pyFoamCloneCase.py <source> <destination>

pyFoamCloneCase.py: error: Too few arguments (2 needed, 0 given)

D:\blueCFD-Core-2.3\ofuser-2.3\run\tutorials\incompressible\simpleFoam>pyFoamCloneCase pitzDaily pitzTest
PyFoam WARNING on line 117 of file D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\CloneCase.py :
 Directory  does not exist. Creating
Traceback (most recent call last):
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam/Scripts/pyFoamCloneCase.py", line 5, in <module>
    CloneCase()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\CloneCase.py", line 32, in __init__
    **kwargs)
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PyFoamApplication.py", line 348, in __init__
    result=self.run()
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\CloneCase.py", line 156, in run
    followSymlinks=self.parser.getOptions().followSymlinks
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\RunDictionary\SolutionDirectory.py", line 309, in cloneCase
    self.execute("find "+name+" -name .svn -exec rm -rf {} \\; -prune")
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Basics\Utilities.py", line 52, in execute
    stdin=PIPE, stdout=PIPE, stderr=STDOUT, close_fds=True)
  File "D:\blueCFD-Core-2.3\ThirdParty-2.3\platforms\linuxmingw-w64\paraview-4.1.0\bin\Lib\subprocess.py", line 637, in __init__
    raise ValueError("close_fds is not supported on Windows "
ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr
```

One solution is to change `close_fds` to `false` in `Utilities.py`, but it hasn't been checked yet if there are any repercussions.

**Comment by wyldckat** [comment]
Bug fixed by the commit mentioned above.
