### ISSUE TITLE
vtkCommonCorePython Module Not Found

### ISSUE THREAD

**Issue by bweems** [blueCFD/PyFoam#6]
PyFoamDisplayBlockMesh does not work because there is no module vtkCommonCorePython.

Error message:

```
$ PyFoamDisplayBlockMesh testCloneCase2/constant/polyMesh/blockMeshDict
Using system-VTK
 Error in C:/Users/Admin/DOCUME~1/blueCFD/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamDisplayBlockMesh.py : FatalError in PyFoam: 'PyFoam FATAL ERROR on line 29 of file C:\Users\Admin\DOCUME~1\blueCFD\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\DisplayBlockMesh.py: Error while importing modules: No module named vtkCommonCorePython'
PyFoam WARNING on line 11 of file C:/Users/Admin/DOCUME~1/blueCFD/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamDisplayBlockMesh.py : Falling back to the old Tkinter-implementation because no PyQT4 was found
```

vtkCommonCorePython.pyd was not in the folder blueCFD/ThirdParty-2.3/platforms/linuxmingw-w64/ParaView-4.1.0/lib/paraview-4.1/site-packages/vtk/tk,which is where DisplayBlockMesh is trying to import it from, but it is in the vtk folder on the same path.  I tried moving vtkCommonCorePython.pyd into the tk folder but this predictably didn't work and resulted in the following error message:

```
PyFoamDisplayBlockMesh testCloneCase2/constant/polyMesh/blockMeshDict
Using system-VTK
PyFoam WARNING on line 11 of file C:/Users/Admin/DOCUME~1/blueCFD/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamDisplayBlockMesh.py : Falling back to the old Tkinter-implementation because no PyQT4 was found
PyFoam WARNING on line 71 of file C:\Users\Admin\DOCUME~1\blueCFD\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\DisplayBlockMesh.py : While reading testCloneCase2/constant/polyMesh/blockMeshDict this happened: SetInput
Traceback (most recent call last):
  File "C:/Users/Admin/DOCUME~1/blueCFD/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamDisplayBlockMesh.py", line 18, in <module>
    DisplayBlockMesh()
  File "C:\Users\Admin\DOCUME~1\blueCFD\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\DisplayBlockMesh.py", line 45, in __init__
    nr=1)
  File "C:\Users\Admin\DOCUME~1\blueCFD\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PyFoamApplication.py", line 348, in __init__
    result=self.run()
  File "C:\Users\Admin\DOCUME~1\blueCFD\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\DisplayBlockMesh.py", line 72, in run
    raise e
AttributeError: SetInput
```

**Comment by wyldckat** [comment]
The two commits indicated above solve part of the problem:
1. The first one includes the necessary path to the environment variable `PYTHONPATH`. You'll need to follow the installation instructions once again.
2. The second commit updates the methods that interact with VTK, making it compatible with the more recent VTK 5.x and 6.x versions, because the old methods have been deprecated in VTK 6.

Problem is that now we stumble upon this issue:

```
$ pyFoamDisplayBlockMesh constant/polyMesh/blockMeshDict
Using system-VTK
PyFoam WARNING on line 11 of file D:/BLUECF~1.3/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamDisplayBlockMesh.py : Falling back to the old Tkinter-implementation because no PyQT4 was found
Traceback (most recent call last):
  File "D:/BLUECF~1.3/ThirdParty-2.3/platforms/linuxmingw-w64/PyFoam/Scripts/pyFoamDisplayBlockMesh.py", line 18, in <module>
    DisplayBlockMesh()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\DisplayBlockMesh.py", line 45, in __init__
    nr=1)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\PyFoamApplication.py", line 348, in __init__
    result=self.run()
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\PyFoam\lib\site-packages\PyFoam\Applications\DisplayBlockMesh.py", line 92, in run
    self.rw = vtkTkRenderWindowInteractor(self.f1, width=400, height=400, rw=self.renWin)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\ParaView-4.1.0\lib\paraview-4.1\site-packages\vtk\tk\vtkTkRenderWindowInteractor.py", line 48, in __init__
    vtkLoadPythonTkWidgets(master.tk)
  File "D:\BLUECF~1.3\ThirdParty-2.3\platforms\linuxmingw-w64\ParaView-4.1.0\lib\paraview-4.1\site-packages\vtk\tk\vtkLoadPythonTkWidgets.py", line 73, in vtkLoadPythonTkWidgets
    interp.call('load', filename, pkgname)
_tkinter.TclError: couldn't load library "vtkRenderingPythonTkWidgets-6.1.dll": this library or a dependent library could not be found in library path
```

This issue is already known and has been reported here: http://www.vtk.org/Bug/view.php?id=14517
I believe that this bug at VTK has a low priority, because the use of Tk is likely to be discontinued sometime in the near future.

The possible and easiest workaround would be to install PyQT4 into the local Python installation, so that `pyFoamDisplayBlockMesh` will use the Qt4 version instead of the Tk one, but I haven't tested this yet.

**Comment by wyldckat** [comment]
Using a custom PyQt4 installation, I've managed to get this working. The commit referenced above fixes the issues related to using VTK 6.x.

Still need to make a package that provides a PyQt4 installation compatible with ParaView's 4.1.0 software stack.

Related to this, still need to check what can be done to create the missing `vtkRenderingPythonTkWidgets-6.1.dll` library.

**Comment by wyldckat** [comment]
PyQt4 packages have been created for integrating with ParaView 4.1.0 on Windows, both 32 and 64-bit. Instructions are provided in the following links:
- Packages to be downloaded: section [Available builds](https://code.google.com/p/unofficial-paraview-dev-install/wiki/PyQt4#Available_builds)
- Installation instructions: section [Installation](https://code.google.com/p/unofficial-paraview-dev-install/wiki/PyQt4#Installation)

Regarding the installation, it can either be integrated into the `PyFoam` installation folder or into the `ParaView-4.1.0` folder.

With this is should now be possible to use `PyFoamDisplayBlockMesh` on Windows.

As for the Tk/Tcl side of the problem, it's somewhat complicated to solve. It requires to perform the [SuperBuild](https://code.google.com/p/unofficial-paraview-dev-install/wiki/Notes410) of ParaView with Tk/Tcl turned on for VTK, as well as using the same Tk/Tcl that is provided with the respective Python 2.7.3. Therefore, it's likely that I'll only test things on Linux using the Tk solution and VTK 6.x, to assess if the changes made on the previous commits are working properly.
